### ISSUE TITLE
why use the matrix calculate the convolution the multiplication is less ?

### ISSUE THREAD

**Issue by victorygogogo** [andravin/wincnn#12]
Gg  using multiplication
an Btd using multiplication
Gg @ Btd using multiplication
At * (Gg @ Btd) using multiplication too.
it confused me .
who can explain it for me ?
@andravin

**Comment by andravin** [comment]
The savings come when you use this algorithm in a convolutional neural network layer.

A 3x3 convolutional layer has C input channels and K output channels, and spatial dimensions HxW. The direct algorithm use HWCK9 multiply accumulates. F(4x4, 3x3) uses (H/4)(W/4)CK(36) = HWCK(2.25) multiply accumulates, in addition to (H/4)(W/4)C(144) arithmetic instructions for the data transform, CK(72) for the filter transform, and (H/4)(W/4)K(100) for the inverse transform.

So the reason the number of arithmetic instructions in the transforms do not matter is that the multiplication stage is O(HWCK) while the transforms are O(HWC), O(CK), and O(HWK). So each of the transforms is less by a factor of K, HW, or C. If all of these quantities are large, then the amount of arithmetic in the transforms is dominated by the multiplication stage.

**Comment by victorygogogo** [comment]
@andravin  thank you .
but another question ,how about stride 2 using winograd ?
is this only support the stride 1 ?

**Comment by andravin** [comment]
Yes, you can use fast algorithms with strided convolutions. See the FAQ: https://github.com/andravin/wincnn/blob/master/FAQ.md

**Comment by victorygogogo** [comment]
xoxoxoxoxox
*2
xox
=
xxxxxx * xx + ooooo * o
there is  some  confuse.
can you  give a  kernel=3 stride=2 example  for 1d and 2d  convlution?y

**Comment by victorygogogo** [comment]
xoxoxoxoxox
*2
xox
=
xxxxxx * xx + ooooo * o
there is  some  confuse.
can you  give a  kernel=3 stride=2 example  for 1d and 2d  convlution? 
x mean what  omean what?

**Comment by andravin** [comment]
For the strided (aka "decimated") convolution example in the FAQ, I was showing how you first decompose the input into 2 different inputs by separating the even and odd elements, which are labeled with the symbols `x` and `o`, respectively.

Also you do the same for the filter.

So if you had input signal `xoxoxox` and 3x1 filter `xox`, and you want a stride 2 convolution, the thing to notice is that, because of the stride, we only multiply `x`s in the input times `x`s in the filter, and likewise for `o`s. So we can separate this into 2 separate (unstrided) convolutions:
`xxxx * xx` + `ooo * o`  

One of the convolutions has a 2 element filter, the other a 1 element filter. You can use a fast convolution algorithm for the 2 element filter (eg: F(2, 2), F(4, 2)).

For 2D convolutions, you can use the same decomposition to yield 4 unstrided convolutions. A stride 2 convolution with a 3x3 filter will become a sum of unstrided convolutions with 2x1, 1x2, 2x2, and 1x1 filters. You can use fast algorithms for the 2x1, 1x2, and 2x2 filters.

The paper cited in the FAQ has more detail, and again, this is covered under the "decimated convolutions" section of you favorite DSP book.
