### ISSUE TITLE
how to get the results order by row

### ISSUE THREAD

**Issue by victorygogogo** [andravin/wincnn#15]
can you give a example about results order by row ? if order by row can get the right result ?

for example about F(4,3)

the results order are all by cols .

because I do not want to do the transpose.

**Comment by andravin** [comment]
Just think about F(4,3) as an algorithm that performs a 1-D convolution (correlation really) of a 3-element filter with a 6-element signal, producing 4 output elements. The algorithm does not know what "row" and "column" means, it is up to you to give it the correct data elements and store the results in the correct location for your application.

This is no different than if you used direct convolution instead of Winograd. The naive algorithm for 1-D direct convolution does not know what rows and columns are.
